services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - ../backend/app:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/research
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
      - postgres
    ports:
      - "8080:80"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: research
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
  pg_data:
