version: "3.9"
services:
  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    environment:
      MODULE_NAME: app.main
    volumes:
      - ../backend/app:/app/app
    depends_on:
      - qdrant
      - postgres
    ports:
      - "8080:80"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: research
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
  pg_data:

restart: unless-stopped
