name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  precommit:
    name: pre-commit (black • ruff • isort)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pre-commit and hooks
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install-hooks

      - name: Run pre-commit on all files
        run: pre-commit run --all-files
